### ISSUE TITLE
go get v4 is not working

### ISSUE THREAD

**Issue by mschneider82** [kamilsk/retry#132]
```
go get -u github.com/kamilsk/retry/v4
package github.com/kamilsk/retry/v4: cannot find package "github.com/kamilsk/retry/v4" in any of:
...
```

**Comment by kamilsk** [comment]
Hi @mschneider82, it works only inside another package with enabled go modules.

```
$ mkdir my-new-package && cd $_
$ go mod init $_
$ go get -u github.com/kamilsk/retry/v4
go: finding github.com/kamilsk/retry/v4 v4.0.3
go: downloading github.com/kamilsk/retry/v4 v4.0.3
```

Thus it's not `go get`able anymore cause `go mod` is supported.

Maybe I have to add this into the docs. Thanks!

**Comment by mschneider82** [comment]
i tried to `go get -u github.com/goreleaser/goreleaser` and got this error, it works now
